### PR TITLE
Make canvases of loss and accuracy plots wider.

### PR DESCRIPTION
**Pull request by pranayaryal**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/56)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for the fix! one tiny comment then I will merge.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[mnist/ui.js, line 44 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-examples/56#-L9kFHOB-uH4WN03vb32:-L9kFHOC8FsgSMBkosyC:b-jdg1xl) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3d2b509b2ddb590a7aa164e6d08ee6cf39960af2/mnist/ui.js#L44)):*
> ```JavaScript
> 
>     const canvas = document.createElement('canvas');
>     canvas.setAttribute('class', 'prediction-canvas');
> ```

can you use `canvas.className = 'prediction-canvas'` here instead of setAttribute?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-examples/56#-:-L9kFUVC1L7nZDJjo8on:bbeyoj9)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-examples/56#-:-L9kKMicEWZgMOZW6PBe:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thank you for this!!

**Comment by pranayaryal** [comment]
No problem, Nikhil.

**Pull request merged**
