### PR TITLE
[For discussion] Upgrade @tensorflow/tfjs dependency: 0.13.3 --> 0.14.0; Fix dtype-related breakages

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/188)

### CODE REVIEW

**Comment by dsmilkov** [comment]
+1. We should also add it to release notes. This improved dtype inference is the right way forward, unfortunately it's breaking, but reverting it is not ideal.

**Comment by dsmilkov** [comment]
Perhaps better is to release a patch version that relaxes the dtype constraint for binary_ops (add/sub/mul...) and matmul, like numpy does, which will unbreak users, and we wanted to do this anyhow.

**Comment by dsmilkov** [comment]
I'm happy to do the relaxing of dtype in ops, EOD today or tomorrow, and shouldn't be much work.

**Comment by caisq** [comment]
Closing this PR in favor of https://github.com/tensorflow/tfjs-core/pull/1432

**Pull request closed without merging**
