### PR TITLE
Add extensive code comments to mnist example

### PR DESCRIPTION
**Pull request by brannondorsey**
I've heavily documented the `mnist/` example as a means of preparing tensorflow.js documentation for my team. The end result is pretty useful and should make understanding CNNs with tensorflow.js a bit easier for beginners. I figured I'd PR these comments upstream with the hopes that others might find them useful as well. I've made 0 code changes, only comment additions :+1:.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92)

### CODE REVIEW

**Comment by brannondorsey** [comment]
I've made capitalization fixes and added periods where needed. I've also made a few minor word choice changes :cat:.

**Comment by tafsiri** [comment]
This is fantastic @brannondorsey :clap: :clap:, Left a few comments to hopefully make some things clearer to readers.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[mnist/index.js, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKeGbRCszfrUMtqwLl:-LEKeGbRCszfrUMtqwLm:bnn9ttk) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L26)):*
> ```JavaScript
> 
> // This is a helper class for drawing loss graphs and MNIST images to the
> // window. You can largely ignore it.
> ```

I'd say "For the purposes of understanding the machine learning bits, you can largely ignore it"

---

*[mnist/index.js, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKePcS54TvgSwuJieR:-LEKePcS54TvgSwuJieS:bxf9hol) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L31)):*
> ```JavaScript
> // Create a sequential neural network model. tf.sequential provides an API for
> // creating "stacked" models where the output from one layer is used as the
> // input to another.
> ```

maybe "input to the next layer"

---

*[mnist/index.js, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKecsy-oUgsGWYW21-:-LEKecsy-oUgsGWYW210:blmzbk0) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L34)):*
> ```JavaScript
> const model = tf.sequential();
> 
> // The first layer of the Convolutional Neural network is our input layer. It
> ```

I tend to think of this layer as not an input layer, rather it is just the first layer of the network or first hidden layer. The input layer is typically just the actual input converted to a tensor. The model kind of abstracts it away, so i'd just remove the term 'input' here.

However @caisq may have a better phrasing 

---

*[mnist/index.js, line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKex1X0zPtrOCx7YNn:-LEKex1X0zPtrOCx7YNo:bwswy37) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L52)):*
> ```JavaScript
> model.add(tf.layers.maxPooling2d({poolSize: [2, 2], strides: [2, 2]}));
> 
> // Our second layer is another convolution, this time with 16 filters.
> ```

I'd just call this the third layer and max pooling the second layer? Else it makes it seem like maxpooling isn't really a layer.

---

*[mnist/index.js, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKf9KmCTqbfBWWcBDt:-LEKf9KmCTqbfBWWcBDu:bob2o9g) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L64)):*
> ```JavaScript
> model.add(tf.layers.maxPooling2d({poolSize: [2, 2], strides: [2, 2]}));
> 
> // Now we flatten our 2D filters into a 1D vector to prepare it for input into
> ```

I'd say we are flattening the output of our previous layers (as opposed to the filters)

---

*[mnist/index.js, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKfQQA368QwKsV6zKa:-LEKfQQA368QwKsV6zKb:bppvtgx) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L85)):*
> ```JavaScript
> // The learning rate defines the magnitude by which we update our weights each
> // training step. The higher the value, the faster our loss values converge,
> // but also the more likely we are to overshoot optimal parameter space regions
> ```

maybe simplify to just "overshoot optimal paramaters when making ..."

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-:-LEKoLHq0t3m74NUkSU4:b1p6a85)*

**Comment by caisq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[mnist/index.js, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKecsy-oUgsGWYW21-:-LEKoiUDDFMuFa6wpB4Y:bswoe9f) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L34)):*
> The input

Maybe word the first sentence as this paragraph as:


The first layer of the convolutional neural network plays a dual role: it is both the input layer of the neural network and a layer that performs the first convolution operation on the input.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92)*

**Comment by brannondorsey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[mnist/index.js, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKfQQA368QwKsV6zKa:-LEL28nXCPi6TA3TtyUQ:b-ugilyw) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L85)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

maybe simplify to just "overshoot optimal paramaters when making ..."
</blockquote></details>

Happy to make this change, but curious if it is a simplicity/wording suggestion or if "overshoot optimal parameter space regions" is actually incorrect? The reason I ask is because I actually find it quite helpful to think of model weight parameters as defining a single point in a huge multidimensional space, and training as moving that point around until it is in a better place. Reasoning about training, and lots of ML tasks, in this spatial way is quite helpful to me and that's why I bring it up here. That is how it comes naturally to me but maybe not everyone.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92)*

**Comment by brannondorsey** [comment]
Thanks for these edits! I've updated the code comments in response to them. Happy to change more per further discussion as well :+1:.

**Comment by tafsiri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[mnist/index.js, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKfQQA368QwKsV6zKa:-LEL6heg3G7o9mc2FYlk:byxdnqv) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L85)):*
<details><summary><i>Previously, brannondorsey (Brannon Dorsey) wrote…</i></summary><blockquote>

Happy to make this change, but curious if it is a simplicity/wording suggestion or if "overshoot optimal parameter space regions" is actually incorrect? The reason I ask is because I actually find it quite helpful to think of model weight parameters as defining a single point in a huge multidimensional space, and training as moving that point around until it is in a better place. Reasoning about training, and lots of ML tasks, in this spatial way is quite helpful to me and that's why I bring it up here. That is how it comes naturally to me but maybe not everyone.
</blockquote></details>

I think the reason i suggested the simplification is that there unless you already have that (spatial) mental model it might be tricky to interpret what 'parameter space regions' are (and there wasn't a description of that spatial model/concept prior to this point). 

Simplifying it here may make it easier to connect 'parameters' to the 'weights' described earlier (like in the next sentence that describes them as weight parameters).

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92)*

**Comment by brannondorsey** [comment]
*[mnist/index.js, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-LEKfQQA368QwKsV6zKa:-LELAdjq9TnqbTOGlMfd:b-q5v0wb) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dd4e4320e85e5d37b73dd49296388618715ffa47/mnist/index.js#L85)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I think the reason i suggested the simplification is that there unless you already have that (spatial) mental model it might be tricky to interpret what 'parameter space regions' are (and there wasn't a description of that spatial model/concept prior to this point). 

Simplifying it here may make it easier to connect 'parameters' to the 'weights' described earlier (like in the next sentence that describes them as weight parameters).
</blockquote></details>

Gotcha. I've made the update :+1:. These comments should be good to go pending any additional edits.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92)*

**Comment by tafsiri** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/92#-:-LELRgYk7RMR8a8YyDr3:b-jbsf8z)*

**Pull request merged**
