### PR TITLE
Added cross-env lib and bumped up Parcel to fix npm runs under Windows

### PR DESCRIPTION
**Pull request by Litee**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/96)

### CODE REVIEW

**Comment by Litee** [comment]
CLA signed

**Comment by tafsiri** [comment]
Thanks for this. I found one issue running the watch task with this configuration.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---

*[addition-rnn/package.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/96#-LEL2Cus3wwJhzMQY7iV:-LEL2Cus3wwJhzMQY7iW:b-hft6rv) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/cb4790820e76537bf167220610a2dfe6821c41b3/addition-rnn/package.json#L16)):*
> ```JSON
>   },
>   "scripts": {
>     "watch": "cross-env NODE_ENV=development parcel --no-hmr --open index.html ",
> ```

From my testing it seems that if using parcel 1.7 or higher, the --open flag needs to go after index.html, else this target doesn't work (see https://github.com/parcel-bundler/parcel/issues/1111). Could you change that here and in the other package.json's

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/96#-:-LEL2sUz0_IduWg6F1CY:b-w3bzmd)*

**Comment by Litee** [comment]
Sure, will check and fix

**Comment by Litee** [comment]
Please do not merge - found couple of unsaved changes

**Comment by Litee** [comment]
Fixed now

**Comment by tafsiri** [comment]
:lgtm_strong: Thanks @litee 

---

Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/96#-:-LEUygtr8UVRl-UfkzBx:b-a8kla3)*

**Pull request merged**
