### PR TITLE
Issue report: cannot build translation

### PR DESCRIPTION
**Pull request by tigercosmos**
by following the readme. `translation` example cannot build.

```sh
yarn
yarn watch # or yarn build
```

error message:
```log
⚠️  Could not load existing sourcemap of "../shared/tfjs-examples.css".
🚨  /home/tigercosmos/tfjs-examples/translation/index.js: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (v8.js:256:7)
    at _default (/home/tigercosmos/tfjs-examples/translation/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/home/tigercosmos/tfjs-examples/translation/node_modules/@babel/core/lib/transformation/normalize-file.js:79:36)
    at normalizeFile.next (<anonymous>)
    at run (/home/tigercosmos/tfjs-examples/translation/node_modules/@babel/core/lib/transformation/index.js:29:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (/home/tigercosmos/tfjs-examples/translation/node_modules/@babel/core/lib/transform-ast.js:26:41)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/tigercosmos/tfjs-examples/translation/node_modules/gensync/index.js:251:28)
    at Function.sync (/home/tigercosmos/tfjs-examples/translation/node_modules/gensync/index.js:89:14)
```

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/581)

### CODE REVIEW

**Comment by jsantell** [comment]
Same error when building `mobilenet` example

**Comment by Mengmianxiaoxia** [comment]
Same error when building mobilenet example +1

**Comment by pierricklee** [comment]
Hi this error occurs in many projects from `mobilenet, translate` to `iris`.

I tried to fix it by adding a space in `index.html` but returns same error. 
Anybody know what happens?

**Comment by pierricklee** [comment]
> 

And also, there is another error in `iris`. The `parcel-bundler` package is supposed to be updated to `~1.12.5`.

It is like this:

```
"devDependencies": {
    ...,
    "parcel-bundler": "~1.12.5",
    ...
}
```

But `iris` still comes to this `../shared/tfjs-examples.css` error.

**Comment by pyu10055** [comment]
These errors should have been fixed during the migration to parcel 2. closing this issue.

**Pull request closed without merging**
