### PR TITLE
Add demo for Angular + TFjs predictive prefetching

### PR DESCRIPTION
**Pull request by twerske**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/460)

### CODE REVIEW

**Comment by twerske** [comment]
@googlebot I consent.

**Comment by mgechev** [comment]
@googlebot I consent.

**Review by lina128 — COMMENTED** [review]
The test is failing, can you change this presubmit.ts file to skip the logic if package.json is not found?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/460#-:-M_Y0SYeByWrJS1n1yoj:b-856xbj)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
Thanks, please also update the repo README file to add entry to the table.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/460#-:-M_Y5YwF3s86igcaX2Ww:b-aracin)* status: 0 of 1 approvals obtained

**Review by lina128 — APPROVED** [review]
This is great, thank you for the contribution @mgechev and @twerske !

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/460#-:-M_c2Q6yCYfj-ur66OQw:bcvby3)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
