### PR TITLE
[Interactive visualizers] Add image classifier support

### PR DESCRIPTION
**Pull request by cbeausei**
Adds support for the following flow:

1. User clicks on one of the proposed test images
2. The image classifier runs on the image
3. Outputs are post-processed, then displayed in the UI

Screnshot:
AgGW96GpspKBCft

Also adds relevant unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/363)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Hi Clement, the UI looks really nice! I left some comments below, mainly around error handling and memory management. It's better to explicitly dispose tensors after they are used, otherwise we don't know whether they get garbage collected, so if the page does many rounds of predictions, it may take up a lot of memory.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-:-MJYyn9k8c5BAPoQv3V3:b-kaomhu)* status: 0 of 1 approvals obtained (waiting on @cbeausei, @lina128, and @pyu10055)

___
*[interactive-visualizers/src/app/app.component.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYvoZL70kew_TcvefZ:-MJYvoZL70kew_Tcvef_:bn6jv59) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L140)):*
> ```XML
>       imageDataURL =
>           imageDataURL.replace('application/octet-stream', 'image/jpg');
>       this.handleInputImage(imageDataURL);
> ```

This method and the fetch method above can throw error, what is the UI behavior in these two cases?
___
*[interactive-visualizers/src/app/app.component.ts, line 177 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYwLYPBCzXYQ1vQV-h:-MJYwLYQB7BVsUZ_NZCd:b-712r2l) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L177)):*
> ```XML
> 
>     // Resize the query image according to the model input shape.
>     imageTensor = tf.image.resizeBilinear(
> ```

Wrap these in tf.tidy, otherwise there can be memory leak because intermediate tensors are not disposed.
___
*[interactive-visualizers/src/app/app.component.ts, line 240 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYyU_M6ny94m8VXgg3:-MJYyU_NBIc83-4EKCAb:bq017wr) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L240)):*
> ```XML
>     const predictions: number[] =
>         await outputTensor.squeeze().array() as number[];
> ```

dispose outputTensor. And when will outputTensor.squeeze() be disposed?
___
*[interactive-visualizers/src/app/app.component.ts, line 246 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYxh3hAvH39MT1NW_c:-MJYxh3hAvH39MT1NW_d:b-whgc0c) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L246)):*
> ```XML
>                                    .output_head_metadata[0];
>     let scoreThreshold = 0.0;
>     if (outputHeadMetadata.score_threshold) {
> ```

if (outputHeadMetadata.score_threshold != null)
___
*[interactive-visualizers/src/app/app.component.ts, line 250 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYxmBh4R7Lzn8x2Hdf:-MJYxmBh4R7Lzn8x2Hdg:b-ts931a) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L250)):*
> ```XML
>     }
>     if (this.labelmap == null) {
>       await this.fetchLabelmap(outputHeadMetadata.labelmap_path);
> ```

What is UI behavior if this method fail?
___
*[interactive-visualizers/src/app/app.component.ts, line 262 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJYy9D7-IG7bGGW6WSI:-MJYy9D7-IG7bGGW6WSJ:b-l390qg) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/dc03e6d2e6e5dbd511ead849af7f8e96f123be96/interactive-visualizers/src/app/app.component.ts#L262)):*
> ```XML
>     }
> 
>     // Sort remaining results.
> ```

// Sort remaining results in descending order.

**Comment by cbeausei** [comment]
Thanks for the review!

I addressed your comments in the above commit:
* added use of `tf.engine().startScope` (and `endScope`) for tensor disposing (in my understanding this is enough, I had tested this on another lib, and sounds to me to be a good fit for both simplicity & readability, but please let me know if you prefer to see tf.tidy and tensor disposing in code!)
* added a UI behavior for the case when the labelmap failed to be fetched (and added a unit test for it)
* added some error handling for test image fetching

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the moving this forward. A have a high level question:
so far seems the main app component is tied with classification task, is there a plan to standardize the visualization component per task? (i.e. classification, object detection, segmentation, etc) The hope is that the visualization component can be more generic and other developers can swap with their own models.

I think tf.tidy will be more standard way to handle automatic intermediate tensor disposal.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-:-MJbl9AUC0K5SbEAMaS5:b8nqw2e)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cbeausei and @pyu10055)

___
*[interactive-visualizers/src/app/app.component.ts, line 247 at r2](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-MJbkkJC1cVckiUWFGSO:-MJbkkJC1cVckiUWFGSP:brfgppv) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/d24e7c469c8b50bc9d198e8faf92bcfb4344b131/interactive-visualizers/src/app/app.component.ts#L247)):*
> ```XML
>     // Start new scope to ensure all tensors created will be then destroyed (see
>     // call to `endScope` below).
>     tf.engine().startScope();
> ```

you can use tf.tidy() instead of declaring scopes.

**Comment by cbeausei** [comment]
Sounds good @ using `tf.tidy`! Changed the code accordingly, and checked the number of tensors remained constant after each inference by running `tf.memory().numTensors`.

Regarding the per-task plan, yes there definitely is!

Basically, the flow is the following:
1. The user loads the visualizer page with a URL query param containg their model metadata, and then knows what's the expected task
2. When the user selects a test image (or whichever test data depending on the specific task), the model runs for the specific task
3. Results are post-processed then displayed according to the specific task

I added some early information in the README.

Here in this commit I implement the flow for image classifiers. And other tasks can then follow smoothly.

**Review by lina128 — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/363#-:-MJc9L0X3Bg7Gc1R-NMK:b-85i648)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @cbeausei)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/363)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @cbeausei and @pyu10055)

**Pull request merged**
