### PR TITLE
[Interactive Visualizers] Add app scaffold

### PR DESCRIPTION
**Pull request by cbeausei**
Result of running the commands:

* `$ npm install -g @angular/cli` (installing angular)
* `$ ng new interactive-visualizers` (creating the app)

Also updated README-s.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/355)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thank you! please make sure license headers are included in all source files.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/355#-:-MIdpfLS0cSpvbpePlbx:brqd1lh)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Comment by cbeausei** [comment]
Thanks! Added the licence to source files.

**Review by lina128 — COMMENTED** [review]
Thank you Clement! Look good to me overall. I left a comment to understand why different ES versions in tsconfig. Also as a general rule, if there's UI change, attach a snapshot of the UI. But I understand this change doesn't include the actual UI just the example from the angular creation process, right? If so, no need to attach the snapshot. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/355#-:-MIdwqLjAGM2XlbtsZA2:bwi4tw8)* status: 0 of 1 approvals obtained (waiting on @cbeausei and @lina128)

___
*[interactive-visualizers/tsconfig.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/355#-MIdt5rQ80s5ZAaTSkY4:-MIdt5rQ80s5ZAaTSkY5:b-c80iu9) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/343a9359de38d8ec1b92daf0d46fbde349bfbb6d/interactive-visualizers/tsconfig.json#L14)):*
> ```jsonc
>     "importHelpers": true,
>     "target": "es2015",
>     "module": "es2020",
> ```

Curious, why do we need es2020 module?
___
*[interactive-visualizers/tsconfig.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/355#-MIduDuC2ba_wNZQJ2SA:-MIduDuC2ba_wNZQJ2SB:b-tp5ipc) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/343a9359de38d8ec1b92daf0d46fbde349bfbb6d/interactive-visualizers/tsconfig.json#L16)):*
> ```jsonc
>     "module": "es2020",
>     "lib": [
>       "es2018",
> ```

For consistency, can we use es2017 everywhere?

**Comment by cbeausei** [comment]
Thanks for the review!

Sg, I changed the ES version to 2017 everywhere (it was just generated this way by Angular).

About UI snapshots, definitely! Will add them along the way. Indeed just not this one as it's empty for now (just the content generated by Angular).

**Comment by lina128** [comment]
Thank you for the change, Clement! The module still has to be ES2015, like here: https://github.com/tensorflow/tfjs/blob/master/tsconfig.json#L3

**Comment by cbeausei** [comment]
Got it! Changed it to es2015!

**Review by lina128 — APPROVED** [review]
Thank you Clement! LGTM!

**Pull request merged**
