### PR TITLE
Add a pure gpu pipeline example.

### PR DESCRIPTION
**Pull request by lina128**
This example demonstrates how to pass along TF.js tensor textures (on GPU) to downstream rendering steps in a pure GPU pipeline.

Demo: https://storage.googleapis.com/tfjs-testing/segmentation-landscape/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/675)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
THanks, this is awesome.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-:-MuNhs_c7ABXrtSOlaLB:boepr5)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[gpu-pipeline/gl-class.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MtxyWAE3jEhdNLm_gpO:-MtxyWAE3jEhdNLm_gpP:b-ullam5) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L1)):*
> ```JavaScript
> // A wrapper class for WebGL texture and its associted framebuffer and utility functions.
> ```

please add license header across the new files.
___
*[gpu-pipeline/gl-class.js, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNg_Ix97ZY0Pl1mtwe:-MuNg_Ix97ZY0Pl1mtwf:bo3wk7p) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L2)):*
> ```JavaScript
> // A wrapper class for WebGL texture and its associted framebuffer and utility functions.
> class GlTextureFramebuffer {
> ```

can this inherit from GLTextureImpl class?
___
*[gpu-pipeline/gl-class.js, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNh8ID2ieaUKeLr68N:-MuNh8ID2ieaUKeLr68O:bb1ozgu) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L145)):*
> ```JavaScript
>       this.proc = new GlShaderProcessor(gl, MASK_SHADER);
>     }
>     process(sharp, mask) {
> ```

should `sharp` be named as frame?
___
*[gpu-pipeline/gl-class.js, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNhDnMA_Kh8T8v8O9U:-MuNhDnMA_Kh8T8v8O9V:b-wune9g) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L148)):*
> ```JavaScript
>       this.proc.startProcessFrame(sharp.width, sharp.height);
>       this.proc.bindTextures(
>           [['sharp', sharp], ['mask', mask]]);
> ```

what is `sharp` referring to? video frame?
___
*[gpu-pipeline/gl-class.js, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNh3Nb0rBX6V9Os7_r:-MuNh3Nb0rBX6V9Os7_s:bbet9ep) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L152)):*
> ```JavaScript
>     }
>     disposeInternal() {
>       super.disposeInternal();
> ```

is this call necessary?
___
*[gpu-pipeline/index.js, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MtxzqzL3kxN7O6hAukX:-MtxzqzL3kxN7O6hAukY:b-dembus) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L23)):*
> ```JavaScript
>     tf.removeBackend('webgl');
>   }
>   // Must be named 'webgl' to match the kernel namespace.
> ```

do you have to remove the webgl backend, I think the simplest is to create a new one and call setBackend()?
___
*[gpu-pipeline/index.js, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNhfGg7mpDbnIc0mAf:-MuNhfGg7mpDbnIc0mAg:b-tjriuf) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L51)):*
> ```JavaScript
>       // this allows the densely packed data to have the same layout as the 
>       // original video content, which simplifies the shader logic. This only
>       // works if the data shape is [1, height, width, 4].
> ```

if the data is only 3 or 1 channel, what should the users do? it would be good to have examples for those.
___
*[gpu-pipeline/index.js, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNg1Cb84r9LmMliRQK:-MuNg1Cb84r9LmMliRQL:bd5d6lg) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L54)):*
> ```JavaScript
>       const tensor = await segmentation[0].mask.toTensor();
>       const data =
>       tensor.dataToGPU({customTexShape: [videoHeight, videoWidth]});
> ```

indentation
___
*[gpu-pipeline/index.js, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNgDVy0k4TIOCg-J6J:-MuNgDVy0k4TIOCg-J6K:b-u3kk3g) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L59)):*
> ```JavaScript
>       // In this case, we just pass through foreground pixels and make background
>       // pixels more transparent.
>       result = applyMask.process(inputTextureFrameBuffer, createTexture(
> ```

const result = 
___
*[gpu-pipeline/ui-util.js, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNfUbA8TAZneb856L9:-MuNfUbA8TAZneb856LA:b-2k532o) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/ui-util.js#L41)):*
> ```JavaScript
>   const gui = new dat.GUI();
> 
>   gui.add(state, 'interpolation', [1, 2, 3, 4, 5, 10]);
> ```

as we have discussed, can you remove the interpolation configurations?

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/675)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[gpu-pipeline/gl-class.js, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuRsRNq5nXQEaf8b74C:-MuRsRNq5nXQEaf8b74D:bmgfe2) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/52a1c013877777b697fb1b0b34d7d1a64ccef665/gpu-pipeline/gl-class.js#L23)):*
> ```JavaScript
>       this.gl_ = gl;
>       this.texture_ = texture;
>       this.width = width;
> ```

follow the same convention (with `_` suffix or not) for all variables.

**Review by jinjingforever — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/675)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

*[a discussion](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuRrhsQ6znpLkUgHz6H:-MuRrhsRAV1NPcHg-3po:b-ggfrie) (no related file):*
This is very cool!  Just curious: is the model API (body-segmentation.min.js) going to be released with the model?

---
___
*[gpu-pipeline/gl-class.js, line 76 at r2](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuRt5GS6KFgzzDUb7V-:-MuRt5GS6KFgzzDUb7V0:bihhmb4) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/52a1c013877777b697fb1b0b34d7d1a64ccef665/gpu-pipeline/gl-class.js#L76)):*
> ```JavaScript
>           gl.ARRAY_BUFFER, Float32Array.from([-1, -1, 1, -1, -1, 1, 1, 1]),
>           gl.STATIC_DRAW);
>   
> ```

nit: I see these in some places here and below. Are they empty spaces? If so please remove.



_Code quote:_
```JavaScript
···
```

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/675)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[gpu-pipeline/gl-class.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MtxyWAE3jEhdNLm_gpO:-MuNz79TD9L2Wd5uNzaJ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L1)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please add license header across the new files.
</blockquote></details>

Done.
___
*[gpu-pipeline/gl-class.js, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNg_Ix97ZY0Pl1mtwe:-MuO-0gHDhsEg6pkiS23:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L2)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can this inherit from GLTextureImpl class?
</blockquote></details>

Done.
___
*[gpu-pipeline/gl-class.js, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNh8ID2ieaUKeLr68N:-MuO-LVl2BKQtTKvA69f:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L145)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should `sharp` be named as frame?
</blockquote></details>

Done.
___
*[gpu-pipeline/gl-class.js, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNhDnMA_Kh8T8v8O9U:-MuO-NCHEET3AeX_FZE0:b-m1t47c) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L148)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is `sharp` referring to? video frame?
</blockquote></details>

Yes. Renamed to frame.
___
*[gpu-pipeline/gl-class.js, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNh3Nb0rBX6V9Os7_r:-MuO-jWn1y9PJNqnP8YR:ba3dfob) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/gl-class.js#L152)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is this call necessary?
</blockquote></details>

Removed
___
*[gpu-pipeline/gl-class.js, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuRsRNq5nXQEaf8b74C:-MuRyEu7-v7qxxFwtRVG:buqmy08) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/52a1c013877777b697fb1b0b34d7d1a64ccef665/gpu-pipeline/gl-class.js#L23)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

follow the same convention (with `_` suffix or not) for all variables.
</blockquote></details>

width and height are public.
___
*[gpu-pipeline/gl-class.js, line 76 at r2](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuRt5GS6KFgzzDUb7V-:-MuRyINd1IkUXATWQ4JM:bb6sh2i) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/52a1c013877777b697fb1b0b34d7d1a64ccef665/gpu-pipeline/gl-class.js#L76)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

nit: I see these in some places here and below. Are they empty spaces? If so please remove.
</blockquote></details>

Ack.
___
*[gpu-pipeline/index.js, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MtxzqzL3kxN7O6hAukX:-MuO466M4cJDTZ7AG8Yl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L23)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

do you have to remove the webgl backend, I think the simplest is to create a new one and call setBackend()?
</blockquote></details>

Done.
___
*[gpu-pipeline/index.js, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNhfGg7mpDbnIc0mAf:-MuO55uZ5V0tr8qQEWY5:bk61ydv) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L51)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

if the data is only 3 or 1 channel, what should the users do? it would be good to have examples for those.
</blockquote></details>

Users need to do the coord transformation to get the correct value. Or they can pad the data to be 4d for convenience. We can add these examples in the API doc.
___
*[gpu-pipeline/index.js, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNg1Cb84r9LmMliRQK:-MuO5azm2SB_p_3vhukO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L54)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.
___
*[gpu-pipeline/index.js, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNgDVy0k4TIOCg-J6J:-MuO5f_p4RNxYAIhfJFC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/index.js#L59)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

const result = 
</blockquote></details>

Done.
___
*[gpu-pipeline/ui-util.js, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/675#-MuNfUbA8TAZneb856L9:-MuO5hCEAXKgJQ_MTxr9:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/474dbacdffe6fee3a2fb2af5c517f1c8e5a256d2/gpu-pipeline/ui-util.js#L41)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

as we have discussed, can you remove the interpolation configurations?
</blockquote></details>

Done.

**Pull request merged**
