### PR TITLE
Add tfdf-adult-gbt demo

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/911)

### CODE REVIEW

**Comment by ahmedsabie** [comment]
@achoum

**Review by pyu10055 — CHANGES_REQUESTED** [review]
can you provide a working demo link? thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-:-NGsFrd10gUv3M7dlBxP:bc3529q)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfdf-adult-gbt/index.html` line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsFmLo15YfPeVRdBDz:-NGsFmLo15YfPeVRdBE-:b-a2jfih) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/index.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

please add license headers
___
*[`tfdf-adult-gbt/index.html` line 9 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsF8qK3S9HSj70kdAT:-NGsF8qK3S9HSj70kdAU:bfbbppi) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/index.html#L9)):*
> ```HTML
> 
>   
>   <script src="https://cdn.jsdelivr.net/npm/jszip"></script>
> ```

this is not needed after Matt's PR?
___
*[`tfdf-adult-gbt/README.md` line 13 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsFS6w4p7tAgaUMQ60:-NGsFS6w4p7tAgaUMQ61:byyvt5v) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/README.md#L13)):*
> ```Markdown
> 2. Save the model (will be exported as a SavedModel).
> 
> 3. Run the model through the [tensorflowjs_converter](https://www.tensorflow.org/js/guide/conversion).
> ```

might be good to provide code snippet for the conversion or link to the tfjs-tfdf doc file.

**Review by ahmedsabie — COMMENTED** [review]
Added

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-:-NGx8Znb66ayNvsZlECt:b-8b11j9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfdf-adult-gbt/index.html` line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsFmLo15YfPeVRdBDz:-NGx8a1w3ZBsY4VWZ43n:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/index.html#L1)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please add license headers
</blockquote></details>

Done.
___
*[`tfdf-adult-gbt/index.html` line 9 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsF8qK3S9HSj70kdAT:-NGx8aKy43dFcvvpoHWF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/index.html#L9)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this is not needed after Matt's PR?
</blockquote></details>

Done.
___
*[`tfdf-adult-gbt/README.md` line 13 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/911#-NGsFS6w4p7tAgaUMQ60:-NGx8azu8126EAiJdUZA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/3139fcf33f36bc02ea8aa36363a2238890b57964/tfdf-adult-gbt/README.md#L13)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

might be good to provide code snippet for the conversion or link to the tfjs-tfdf doc file.
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/911)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
