### PR TITLE
29, 30 and 31 are valid day numbers.

### PR DESCRIPTION
**Pull request by emiperez**
Include all valid dates in the training examples.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/248)

### CODE REVIEW

**Comment by caisq** [comment]
1. @emiperez Can you sign the CLA?
2. Can you run the unit tests of the date-conversion-attention example with `yarn test`? I suspect that some test will fail. in which please fix them.

**Comment by emiperez** [comment]
>     1. @emiperez Can you sign the CLA?
done
>     2. Can you run the unit tests of the date-conversion-attention example with `yarn test`? I suspect that some test will fail. in which please fix them.
I get the following error: 
Error: Cannot find any save handlers for URL 'file:///tmp/tmp-5720LhKWyeug7xI8'
[...]
at UserContext.it (/home/emiperez/dev/git/tfjs-examples/date-conversion-attention/model_test.js:66:17)

The folder "/tmp/tmp-5720LhKWyeug7xI8" is created, but there are no files inside.
I have searched on the Internet about that error, but I did not find anything that helped.

**Comment by emiperez** [comment]
Got it working by removing the following line from package.json:
""@tensorflow/tfjs": "^1.0.0", 
I'll add soon another pull request with that change. After changing it, no errors found in tests:
27 specs, 0 failures
Finished in 3.027 seconds
Done in 4.39s.

**Comment by emiperez** [comment]
After updating to the last night's version of the project, no needed to change package.json. Tests passed without returning any failures:
~/dev/git/tfjs-examples/date-conversion-attention$ yarn test
yarn run v1.15.2
$ babel-node run_tests.js
2019-03-15 18:28:21.143107: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-15 18:28:21.180145: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3599965000 Hz
2019-03-15 18:28:21.181070: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5582e92460b0 executing computations on platform Host. Devices:
2019-03-15 18:28:21.181111: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Started
(node:4712) Warning: N-API is an experimental feature and could change at any time.
.......................Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
Epoch 1 / 2
eta=0.0 => 
145ms 48422us/step - loss=8.91 
Epoch 2 / 2
eta=0.0 => 
87ms 29001us/step - loss=8.90 
.Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
Layer lstm_LSTM4 was passed non-serializable keyword arguments: [object Object]. They will not be included in the serialized model (and thus will be missing at deserialization time).
.Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
Orthogonal initializer is being called on a matrix with more than 2000 (16384) elements: Slowness may result.
..


27 specs, 0 failures
Finished in 2.881 seconds
Done in 4.32s.

**Comment by emiperez** [comment]
I am sorry, I already deleted the branch, (I am novice at using GitHub) so I do not know how to edit it.
Besides, I have a mess with my email addresses and Google accounts, so I am having problems to sign the CLA.
So if you want, just close/reject this pull request. And if anybody wants to do the same pull request, I will not oppose it.

**Comment by caisq** [comment]
@emiperez Thanks for the info. I'll help you submit the change in another PR soon.

**Pull request closed without merging**
