### PR TITLE
[Interactive visualizers] Improve test images section

### PR DESCRIPTION
**Pull request by cbeausei**
This:

* adds support for running on drag&drop, or file selected images
* keeps track of the currently selected image
* automatically triggers running on the first test image at page load

Screen video capture: 
demo

Also adds a unit test for file upload reads.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/365)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/365)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cbeausei, @lina128, and @pyu10055)

___
*[interactive-visualizers/src/app/app.component.html, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-MJmKjRJ3sd9dIoO_U1F:-MJmKjRJ3sd9dIoO_U1G:bojea2y) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/2c76a43b6106957adfcc1b3fadd0539c2c0de437/interactive-visualizers/src/app/app.component.html#L51)):*
> ```HTML
>         <div class="TestImageContainer" *ngFor="let testImage of testImages; let i = index"
>              (click)="testImageSelected(testImage.imageUrl, i)">
>            ```

Just curious, whether this conditional class can be written more concisely using ng-class, something like:
```
<img ng-class="{'TestImage': imageSelectedIndex !== i, 'TestImageSelected': imageSelectedIndex === i}"
```
___
*[interactive-visualizers/src/app/app.component.ts, line 169 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-MJmLlw2-DfNMQPt1ZU-:-MJmLlw2-DfNMQPt1ZU0:b-obm8ne) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/2c76a43b6106957adfcc1b3fadd0539c2c0de437/interactive-visualizers/src/app/app.component.ts#L169)):*
> ```XML
>       for (const imageFile of Array.from(element.files)) {
>         if (!imageFile.type.match('image*')) {
>           return;
> ```

Why not skip?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/365)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @cbeausei, @lina128, and @pyu10055)

___
*[interactive-visualizers/src/app/app.component.html, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-MJmKjRJ3sd9dIoO_U1F:-MJrg15g-R1GzTe36f5M:b32v57) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/2c76a43b6106957adfcc1b3fadd0539c2c0de437/interactive-visualizers/src/app/app.component.html#L51)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Just curious, whether this conditional class can be written more concisely using ng-class, something like:
```
<img ng-class="{'TestImage': imageSelectedIndex !== i, 'TestImageSelected': imageSelectedIndex === i}"
```
</blockquote></details>

+1
___
*[interactive-visualizers/src/app/app.component.html, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-MJrh8DPAOpR5u_Rzlql:-MJrh8DPAOpR5u_Rzlqm:b-4zmt66) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/2c76a43b6106957adfcc1b3fadd0539c2c0de437/interactive-visualizers/src/app/app.component.html#L61)):*
> ```HTML
>         <div class="TestImageContainer" *ngFor="let uploadedImage of uploadedImages; let i = index"
>              (click)="testImageSelected(uploadedImage, testImages.length + i)">
>            ```

use ng-class here as Na have suggested.
___
*[interactive-visualizers/src/app/app.component.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-MJrgCEZELsDg2fwwpwJ:-MJrgCEZELsDg2fwwpwK:b-i4a1eq) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/2c76a43b6106957adfcc1b3fadd0539c2c0de437/interactive-visualizers/src/app/app.component.ts#L140)):*
> ```XML
>    * On click on a test image.
>    */
>   async testImageSelected(imageUrl: string, index): Promise<void> {
> ```

type or default value for index param

**Review by pyu10055 — APPROVED** [review]
Looks great, thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/365#-:-MJrhXTY7NAtCNxc9gMO:b-qbxl94)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @cbeausei and @lina128)

**Comment by cbeausei** [comment]
Thanks for the review! Addressed comments.
Nice to use ngClass indeed!

**Pull request merged**
