### PR TITLE
Add tfjs-react-native example apps

### PR DESCRIPTION
**Pull request by jinjingforever**
This PR adds pose-detection (expo) and image-classification (expo and react-native-cli) react native apps. There are a lot of boilerplate code/files that are auto-generated by expo/rn-cli. Please feel free to only take a look at the `README.md` files and the `App.tsx` files. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/608)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for creating this RN example, much needed.

A high level question, should the generated file be checked in? can we provide the documentation to generate those files?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-:-Mk8H4RqBAyGT-Zw7zVi:b-xkew9z)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[react-native/image-classification/expo/app.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-Mk8GkSCCt8c-fg0n84R:-Mk8Gi8-CPPt_y3ibolp:b25y0h5) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/310d0030877fe881742b167904f10dfc5c66fcb6/react-native/image-classification/expo/app.json#L2)):*
> ```
> :
> ```
posenet is not for image-classification? should it be mobilenet?

**Review by jinjingforever — COMMENTED** [review]
I think they need to be checked in since different version of Expo/react native CLI might generate different files. Also, I actually did some editing to some of those files to make the app work (e.g. add native linking for certain packages). 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-:-Mk8OJAD1Lgt3yyJ-mf9:b-ppci3e)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[react-native/image-classification/expo/app.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-Mk8GkSCCt8c-fg0n84R:-Mk8Oizz3EmADgv0VGy7:bhmhk5s) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/310d0030877fe881742b167904f10dfc5c66fcb6/react-native/image-classification/expo/app.json#L2)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> :
> ```
posenet is not for image-classification? should it be mobilenet?
</blockquote></details>

Nice catch! Done.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/608)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[react-native/README.md, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-Mk8RiX74rJE-PTVk_2M:-Mk8RiX74rJE-PTVk_2N:b-ndvgnj) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/310d0030877fe881742b167904f10dfc5c66fcb6/react-native/README.md#L8)):*
> ```Markdown
> 
> As of Sep 2021, `tfjs-react-native` supports the following package version
> combination. Other versions (e.g. `react-native` 0.65.1) might cause crash.
> ```

Do we know the reasons for the crash?

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-examples/608)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[react-native/README.md, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-examples/608#-Mk8RiX74rJE-PTVk_2M:-Mk8TB3XEL6o7sgHiUoc:b44fbk) ([raw file](https://github.com/tensorflow/tfjs-examples/blob/310d0030877fe881742b167904f10dfc5c66fcb6/react-native/README.md#L8)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Do we know the reasons for the crash?
</blockquote></details>

Sorry, not entirely sure why.. When I have time I will probably need to file an issue for expo.

**Pull request merged**
